services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: python_app
    hostname: python_app

    volumes:
      - ./src:/app
    
    working_dir: /app
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development