services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      args:
        USERNAME: "$USER"
        USER_UID: "$USER_UID"
        USER_GID: "$USER_GID"
    container_name: python_app
    hostname: python_app

    volumes:
      - .:/app
      - /home/$USER/.ssh:/home/$USER/.ssh
      - /home/$USER/.gitconfig:/home/$USER/.gitconfig
    
    working_dir: /app
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development